"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-development-only",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'rest_framework',
    'shop',
    'django_filters',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv(
            "DB_NAME",
            "shop_db"
        ),
        "USER": os.getenv(
            "DB_USER",
            "shop_user"
        ),
        "PASSWORD": os.getenv(
            "DB_PASSWORD",
            "Password123"
        ),
        "HOST": os.getenv(
            "DB_HOST",
            "localhost"
        ),
        "PORT": os.getenv(
            "DB_PORT",
            "5432"
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

JWT_SECRET_KEY = SECRET_KEY
JWT_ALGORITHM = "HS256"
JWT_ACCESS_TOKEN_LIFETIME = 60 * 60 * 6 
JWT_REFRESH_TOKEN_LIFETIME = 60 * 60 * 24 * 7

# Redis-backed JWT revocation and per-user logout state.
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
REDIS_TOKEN_KEY_PREFIX = os.getenv("REDIS_TOKEN_KEY_PREFIX", "graphql-shop:tokens")
REDIS_SOCKET_TIMEOUT = float(os.getenv("REDIS_SOCKET_TIMEOUT", "2"))

REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL", "redis://127.0.0.1:6379/1")
CATALOG_CACHE_TIMEOUT = int(os.getenv("CATALOG_CACHE_TIMEOUT", "300"))

RATE_LIMIT_REDIS_URL = os.getenv("RATE_LIMIT_REDIS_URL", "redis://127.0.0.1:6379/4")
ORDER_RATE_LIMIT_KEY_PREFIX = os.getenv(
    "ORDER_RATE_LIMIT_KEY_PREFIX", "graphql-shop:order-rate-limit"
)
ORDER_RATE_LIMIT_REQUESTS = int(os.getenv("ORDER_RATE_LIMIT_REQUESTS", "3"))
ORDER_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("ORDER_RATE_LIMIT_WINDOW_SECONDS", "3600")
)
ORDER_RATE_LIMIT_TRUST_PROXY = os.getenv(
    "ORDER_RATE_LIMIT_TRUST_PROXY", "false"
).lower() in {"1", "true", "yes", "on"}


CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL", "amqp://shop:shop_password@127.0.0.1:5672//"
)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/3")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "300"))
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# RabbitMQ 4 rejects the transient non-exclusive queues used by Celery's
# remote-control pidbox. This application does not use inspect/control commands.
CELERY_WORKER_ENABLE_REMOTE_CONTROL = os.getenv(
    "CELERY_WORKER_ENABLE_REMOTE_CONTROL", "false"
).lower() in {"1", "true", "yes", "on"}
CELERY_WORKER_CANCEL_LONG_RUNNING_TASKS_ON_CONNECTION_LOSS = os.getenv(
    "CELERY_WORKER_CANCEL_LONG_RUNNING_TASKS_ON_CONNECTION_LOSS", "true"
).lower() in {"1", "true", "yes", "on"}


ORDER_PENDING_TIMEOUT_SECONDS = int(os.getenv("ORDER_PENDING_TIMEOUT_SECONDS", "1800"))
ORDER_CANCELLATION_SCAN_SECONDS = int(os.getenv("ORDER_CANCELLATION_SCAN_SECONDS", "60"))
CELERY_BEAT_SCHEDULE = {
    "cancel-expired-pending-orders": {
        "task": "shop.tasks.cancel_expired_pending_orders",
        "schedule": ORDER_CANCELLATION_SCAN_SECONDS,
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "KEY_PREFIX": "graphql-shop",
        "TIMEOUT": CATALOG_CACHE_TIMEOUT,
        "OPTIONS": {
            "socket_connect_timeout": REDIS_SOCKET_TIMEOUT,
            "socket_timeout": REDIS_SOCKET_TIMEOUT,
        },
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "shop.rest_api.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Email is printed by the Celery worker in local development instead of being sent.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "orders@graphql-shop.local")
